#pragma warning disable 1591
// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.17020
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

[assembly: Android.Runtime.ResourceDesignerAttribute("CData.DynamicsCRM.demo.Resource", IsApplication=true)]

namespace CData.DynamicsCRM.demo
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int monoandroidsplash = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f050005
			public const int ConnectionProperties = 2131034117;
			
			// aapt resource value: 0x7f050001
			public const int Details = 2131034113;
			
			// aapt resource value: 0x7f050007
			public const int Execute = 2131034119;
			
			// aapt resource value: 0x7f050004
			public const int GetTables = 2131034116;
			
			// aapt resource value: 0x7f050000
			public const int Input1 = 2131034112;
			
			// aapt resource value: 0x7f050008
			public const int QueryText = 2131034120;
			
			// aapt resource value: 0x7f050009
			public const int Result = 2131034121;
			
			// aapt resource value: 0x7f05000a
			public const int Tables = 2131034122;
			
			// aapt resource value: 0x7f050003
			public const int TestButton = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int relativeLayout1 = 2131034114;
			
			// aapt resource value: 0x7f050006
			public const int relativeLayout2 = 2131034118;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int ConnectionItem = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int Details = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Query = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Tables = 2130903044;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f040000
			public const int Mono_Android_Theme_Splash = 2130968576;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591