// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace iso_demo
{
	public partial class ConnectionCell : UITableViewCell
	{
		public ConnectionCell (IntPtr handle) : base (handle)
		{
		}
	}
}